### ISSUE TITLE
Authentication exception

### ISSUE THREAD

**Issue by Cypaubr** [markitosgv/JWTRefreshTokenBundle#187]
I followed the guide to setup the bundle and when I request a new token I get a 401 error:
```json
{
    "code": 401,
    "message": "An authentication exception occurred."
}
```

Here is the bundle configuration:
```yml
gesdinet_jwt_refresh_token:
  ttl: 2592000
  ttl_update: true
  user_identity_field: email
  manager_type: mongodb
  refresh_token_class: App\Document\RefreshToken
```

Here is my security.yml:
```yml
security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Document\User:
            algorithm: auto
    providers:
        user_mongo:
            mongodb:
                class: App\Document\User
                property: email
    role_hierarchy:
        ROLE_RIDER: ROLE_USER
        ROLE_SELLER: ROLE_USER
        ROLE_TESTER: ROLE_USER
        ROLE_MANAGER: ROLE_USER
        ROLE_ADMIN: ROLE_USER, ROLE_SELLER
        ROLE_SUPER_ADMIN: ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            provider: user_mongo
            form_login:
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api_refresh:
            pattern: ^/api/token/refresh
            stateless: true
            anonymous: true

        api_doc:
            pattern: ^/api/doc
            anonymous: true
            provider: user_mongo

        api:
            pattern: ^/api
            stateless: true
            anonymous: ~
            provider: user_mongo
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            anonymous: ~
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
                provider: user_mongo
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
            logout:
                invalidate_session: true
                path: /logout


    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api/ping$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token/refresh , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/frontendconfiguration, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/doc, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/admin, role: ROLE_ADMIN }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_ADMIN }
```
And here is my RefreshToken document:
```
<?php

namespace App\Document;

use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;
use Gesdinet\JWTRefreshTokenBundle\Document\AbstractRefreshToken;

/**
 * Class RefreshToken
 * @package App\Document
 * @MongoDB\Document()
 */
class RefreshToken extends AbstractRefreshToken
{
    /**
     * @var string
     * @MongoDB\Id()
     */
    protected $id;

    /**
     * @var \DateTime
     * @MongoDB\Field(type="date")
     */
    protected $valid;

    /**
     * @return string
     */
    public function getId(): string
    {
        return $this -> id;
    }

    /**
     * @param string $id
     * @return RefreshToken
     */
    public function setId(string $id): RefreshToken
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @param \DateTime $valid
     */
    public function setValid($valid): void
    {
        $this->valid = $valid;
    }
}
```
