### ISSUE TITLE
Usage with multiple entity managers

### ISSUE THREAD

**Issue by MartianGreed** [markitosgv/JWTRefreshTokenBundle#212]
When using the bundle with multiple entity managers, the mapping is bound to the default mapping context.
In order to make it work in production mode : 

- Create an entity class :
```
use Doctrine\ORM\Mapping as ORM;
use Gesdinet\JWTRefreshTokenBundle\Entity\AbstractRefreshToken;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="Gesdinet\JWTRefreshTokenBundle\Entity\RefreshTokenRepository")
 * @UniqueEntity("refreshToken")
 */
class RefreshToken extends AbstractRefreshToken
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    protected $id;

    public function getId(): int
    {
        return $this->id;
    }
}
```
- Add bundle mapping to your entity manager mapping:
```
doctrine:
    orm:
        entity_managers:
            your_manager:
                gesdinet_orm:
                     type: xml
                     mapping: true
                     dir: '%kernel.project_dir%/vendor/gesdinet/jwt-refresh-token-bundle/Resources/config/orm/doctrine-orm'
                     is_bundle: false
                     prefix: Gesdinet\JWTRefreshTokenBundle\Entity
```
- Configure the bundle
```
gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\RefreshToken
  object_manager: doctrine.orm.your_manager_entity_manager
```

Hope this may help !
Cheers

**Comment by bertoost** [comment]
Hi @MartianGreed 
I am wondering how I can use this for a multi-tenant setup.

This is my setup (basically)
- Main database (containing "tenant" table) with alle tenants
- Per tenant database
- Two entity managers (default & tenant)
- An event subscriber to change the connection at request & at console (adds `--tenant=<name>` and switching connections)
- Based on hostnames:
- - http://api.main-domain.tld/
- - http://<tenant-name>.api.main-domain.tld/
- Two API endpoints with JWT token authentication, configured in security.yaml

The main database is used to register all tenants and general stuff for my application
The "per tenant" databases containing the tenant specific stuff
Both (eq. all) API endpoints must be authenticated by a JWT token
But since I use separated databases for each tenant, I am required to generate User records and so JWT refresh tokens per tenant. But I am wondering how to achieve this with this bundle.

Would mind to think with me? :-) Thanks in advance.

**Comment by MartianGreed** [comment]
Hi ! 
By tenant, you mean "n" numbers of tenant, which is not a known number by default ?

If that's the case, I suggest that you create jwt tokens and registers refresh into the main database. Then "tenant" applications authenticate through this gateway which is handled by your main application.

What do you think ?

**Comment by bertoost** [comment]
Thanks for your reply!
It's correct, that I don't know the number of tenants.
Therefore I want to keep users (and so, tokens) in the tenant database, not the main database.
I have defined only one tenant connection and entity_manager, and with a request listener I switch the connection details (which are based on the default, but could differ, per tenant, if I would)

Also my main database will contain users and tokens, and I don't want to mix them up. The main reason for this approach is to separate each tenants' data in a physical separated database.

I have managed to get it working perfectly when I configure like;

```yaml
gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\Tenant\UserRefreshToken
  object_manager: doctrine.orm.tenant_entity_manager
```

But I also should have this one;

```yaml
gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\Main\UserRefreshToken
  object_manager: doctrine.orm.default_entity_manager
```

At the end, the tenant user will also have more details and other details than the "main" user etc.
