### ISSUE TITLE
Missing "controller: gesdinet.jwtrefreshtoken::refresh" in README for Symfony 5

### ISSUE THREAD

**Issue by algorun77** [markitosgv/JWTRefreshTokenBundle#281]
Hello,

Sorry if it's not really an issue but there is a problem with the documentation ([https://github.com/markitosgv/JWTRefreshTokenBundle#step-3-symfony-53](https://github.com/markitosgv/JWTRefreshTokenBundle#step-3-symfony-53).

I've been confused when I tried to implement this bundle into a Symfony 5 project because I got an error saying: "**Unable to find the controller for path "/api/token/refresh". The route is wrongly configured.**".
After digging into the issues, I found out that for the previous version of Symfony (< 5.3), the configuration in the routes file was something like :
```yaml
# config/routes.yaml
gesdinet_jwt_refresh_token:
    path:       /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
# ...
```

But for Symfony +5.3, the "controller" part is omitted, giving the previous error. If this is a mistake, would you consider updating the README to reflect the correct configuration ?

I'm using:
- Symfony 5.3.6
- lexik/jwt-authentication-bundle v2.12.6
- gesdinet/jwt-refresh-token-bundle v0.12.0

Thanks a lot!
