### ISSUE TITLE
Unrecognized option "cookie"

### ISSUE THREAD

**Issue by abeal-hottomali** [markitosgv/JWTRefreshTokenBundle#288]
Hi,

I'm trying to use the http-only cookie support in this bundle.  I've set up the following for bundle configuration:
```yaml
gesdinet_jwt_refresh_token:
    user_identity_field: email
    user_provider: security.user.provider.concrete.app_user_provider
    # Time to live for refresh token (one day)
    ttl: 86400
    cookie:
        enabled: true
        same_site: lax               # default value
        path: /                      # default value
        domain: null                 # default value
        http_only: true              # default value
        secure: true                 # default value
        remove_token_from_body: true # default value
```
When I cache-clear with this, however, I get the following:
```bash
!!    Unrecognized option "cookie" under "gesdinet_jwt_refresh_token". Available
!!    options are "doctrine_mappings", "entity_manager", "firewall", "manager_typ
!!    e", "object_manager", "refresh_token_class", "refresh_token_entity", "singl
!!    e_use", "token_parameter_name", "ttl", "ttl_update", "user_checker", "user_
!!    identity_field", "user_provider".
```
Looking at `\Gesdinet\JWTRefreshTokenBundle\DependencyInjection\Configuration`, I don't see where 'cookie' is established as an option, so although it seems the [documentation](https://github.com/markitosgv/JWTRefreshTokenBundle#configure-refresh-token-in-cookie) for this is incorrect, I'm not exactly sure what to set here.  Can you advise?

Tested with version 0.12, as well as 1.0.0-beta4.

**Comment by abeal-hottomali** [comment]
Update: it looks like the cookie support may have been added [here](https://github.com/markitosgv/JWTRefreshTokenBundle/commit/ef3236685b844d9986639bc634985af99e0fb679), so that may mean it's still not in a tagged release.  If that's the case, please feel free to close this issue, as this will self-resolve in time.

**Comment by Jayfrown** [comment]
@abeal-hottomali Yup, the code and documentation have already been merged to master, but there hasn't been a release yet since then.

**Comment by byhaskell** [comment]
Hello. Is there information when it will be available? You do it according to the documentation, but try it - it doesn't work yet.

**Comment by Jayfrown** [comment]
Currently, the latest release is `v1.0.0-beta4`, which was released before this feature was merged.

By default, you're reading the documentation on the master branch, where this feature is indeed available. Until it is included in a release, you could pull the `dev-master` version and try it out.

Looking at the release history, it does not seem to follow a release cycle / schedule so I cannot tell when a new version will be released.

**Comment by byhaskell** [comment]
@Jayfrown , Thanks for your prompt feedback.

**Comment by abeal-hottomali** [comment]
@byhaskell , I haven't confirmed, but I'd suspect the [v0.12](https://github.com/markitosgv/JWTRefreshTokenBundle/tree/v0.12) release would still contain the correct documentation for the non-master branch?  You could give that a try.  

I've got it working for that version on my end.  If it helps, here's the config I'm using (Symfony/API Platform)
```yaml
# config/packages/security.yaml
security:
    firewalls:
        # Required by gesdinet/jwt-refresh-token-bundle v0.12.0
        api_token_refresh:
            pattern: ^/authentication_token/refresh
            stateless: true
```

```yaml
# config/packages/gesdinet_jwt_refresh_token.yaml
gesdinet_jwt_refresh_token:
    firewall: api_token_refresh
    user_identity_field: email
    # Time to live for refresh token (one day)
    ttl: 86400
    user_provider: security.user.provider.concrete.app_user_provider
```
