### ISSUE TITLE
Symfony 5.4 error AbstractGuardAuthenticator

### ISSUE THREAD

**Issue by alexandre-lxi** [markitosgv/JWTRefreshTokenBundle#294]
Since Symfony 5.4, I have an error with the bundle. 

```
Attempted to load class "AbstractGuardAuthenticator" from namespace "Symfony\Component\Security\Guard".
Did you forget a "use" statement for another namespace?
```

`class RefreshTokenAuthenticator extends AbstractGuardAuthenticator`

Could you help me to update the bundle ?

**Comment by mbabker** [comment]
Ensure you have `symfony/security-guard` installed.  Note, the Security Guard component is deprecated in Symfony 5.4 and isn't supported in Symfony 6.

**Comment by ajay-gupta** [comment]
`symfony/security-guard` is removed in Symfony 6. What is the workaround for this?

**Comment by mbabker** [comment]
Update your app to use the newer `refresh_jwt` authenticator.

**Comment by ajay-gupta** [comment]
Already using the the newer `refresh_jwt ` authenticator.

refresh:
            pattern:  ^/api/token/refresh
            stateless: true
            refresh_jwt: ~

**Comment by mbabker** [comment]
If you're getting an error about the `Symfony\Component\Security\Guard\AbstractGuardAuthenticator` class missing, then something's still trying to use it (maybe not this bundle specifically but somewhere in your app).  Try to get a full stack trace for the error to figure out what's calling it, that will help greatly in finding the source of the problem.

For this bundle's CI, `symfony/security-guard` is [explicitly removed](https://github.com/markitosgv/JWTRefreshTokenBundle/blob/e963f736079214627afb2a0c36386ccd0b56338a/.github/workflows/run-tests.yml#L54-L56) before running the tests in the Symfony 6 environment.  So there is a bit of a sanity check here with the tests to make sure that nothing's trying to use the Security-Guard component in an unsupported environment.

**Comment by ajay-gupta** [comment]
Yes, I traced it is used in `controller: gesdinet.jwtrefreshtoken::refresh` 
```
gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
```

**Comment by mbabker** [comment]
Remove the `controller:` line from the route definition, it’s not needed with the newer authenticator.

**Comment by ajay-gupta** [comment]
Without `controller:` getting this error:
`Unable to find the controller for path "/api/token/refresh". The route is wrongly configured.`

**Comment by mbabker** [comment]
You shouldn't need it, https://github.com/markitosgv/JWTRefreshTokenBundle#define-the-refresh-token-route is pretty much the exact same thing I'm saying here with removing the controller key.  https://github.com/markitosgv/JWTRefreshTokenBundle/issues/255#issuecomment-931211151 is the only other time I've seen that one referenced and there wasn't really a "fix" shared beyond just rebuilding the route configuration.

**Comment by darthf1** [comment]
I'm in the same boat. Had the same initial config (route with controller), removed the controller part and then I get
```
Unable to find the controller for path "/api/token/refresh". The route is wrongly configured.
```

routes:
```yaml
gesdinet_jwt_refresh_token:
  path: /v1/login/refresh
```

config:
```yaml
gesdinet_jwt_refresh_token:
  single_use: false
  ttl: 2592000
  cookie:
    enabled: true
    same_site: strict
    path: /
    domain: '%env(string:resolve:FRONTEND_DOMAIN)%'
    http_only: true
    secure: true
    remove_token_from_body: true
```

**Comment by mbabker** [comment]
> `Unable to find the controller for path "/api/token/refresh".`

> `path: /v1/login/refresh`

Double-check everything in your configuration and whatever's supposed to be calling the refresh endpoint.  Your configuration says the path is `/v1/login/refresh` but something is trying to use the `/api/token/refresh` path.

**Comment by darthf1** [comment]
Yeah my bad that's a copy paste error. (I edited my message a few times). But I found the error pops up when no refresh token is set in the request.

**Comment by vandal-kherson** [comment]
> You shouldn't need it, https://github.com/markitosgv/JWTRefreshTokenBundle#define-the-refresh-token-route is pretty much the exact same thing I'm saying here with removing the controller key. [#255 (comment)](https://github.com/markitosgv/JWTRefreshTokenBundle/issues/255#issuecomment-931211151) is the only other time I've seen that one referenced and there wasn't really a "fix" shared beyond just rebuilding the route configuration.

No, It doesn't work without controller parameter

**Comment by D3lph1** [comment]
Same problem. I have to dive into sources and here is what I found out. Just leave the explanation and solution here.

As we can see in [RefreshTokenAuthenticator](https://github.com/markitosgv/JWTRefreshTokenBundle/blob/master/Security/Http/Authenticator/RefreshTokenAuthenticator.php) supports() method returns `false` when there is no refresh token in a request:

```php
public function supports(Request $request): bool
{
    return null !== $this->extractor->getRefreshToken($request, $this->options['token_parameter_name']);
}
```
so when no token present the authenticator will be skipped and router will fallback to `gesdinet.jwtrefreshtoken::refresh` action.

[Bundle's container configuration](https://github.com/markitosgv/JWTRefreshTokenBundle/blob/1167006f2973064a81f1671e89c3c495969c6a50/Resources/config/services.php#L91) says that `gesdinet.jwtrefreshtoken` alias refer to [RefreshToken](https://github.com/markitosgv/JWTRefreshTokenBundle/blob/master/Service/RefreshToken.php) service which is deprecated and depends on AbstractGuardAuthenticator (this class was removed in Symfony 6).

To solve the problem you need simply define your own fallback endpoint. For example:

```php
namespace App\Controller;

class LoginController extends AbstractController
{
    //
    public function refresh(): JsonResponse
    {
        return new JsonResponse(['msg' => 'JWT refresh token not found'], Response::HTTP_UNAUTHORIZED);
    }
    //
}
```

```yaml
gesdinet.jwt_refresh_token:
    path:       /token/refresh
    controller: App\Controller\LoginController::refresh
```

**Comment by mbabker** [comment]
That's the exact scenario https://github.com/markitosgv/JWTRefreshTokenBundle/pull/303 fixes.

**Comment by blosky01** [comment]
I´m using symfony 6 and a I have the same problem `Attempted to load class "AbstractGuardAuthenticator" from namespace "Symfony\Component\Security\Guard".
Did you forget a "use" statement for another namespace?
`
Someone know how to fix this error?

**Comment by mbabker** [comment]
The 1.1 release should fix this.

**Comment by valentin-harrang** [comment]
I use the 1.1 release with Symfony 6 and I have this error:

> Attempted to load class "AbstractGuardAuthenticator" from namespace "Symfony\Component\Security\Guard".
> Did you forget a "use" statement for another namespace?

security.yaml:

```
security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        admin:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            provider: admin
            entry_point: form_login
            custom_authenticators:
                - App\Security\AdminAuthenticator
            form_login:
                provider: admin
                login_path: admin_login
                check_path: admin_login_check
                failure_path: admin_login
                default_target_path: admin
                use_forward: false
                use_referer: true
                enable_csrf: true
            logout:
                path: admin_logout
                target: admin_login

        login:
            pattern: ^/api/login$
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        refresh:
            pattern: ^/api/token/refresh
            stateless: true

        api:
            pattern: ^/api
            stateless: true
            entry_point: jwt
            jwt: ~
            refresh_jwt:
                check_path: /api/token/refresh
            logout:
                path: api_token_invalidate

    access_control:
        - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }
        - { path: ^/api/docs, roles: ROLE_ADMIN }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
```

routes.yaml:

```
api_login_check:
    path: /api/login
    methods: ['POST']

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh

api_token_invalidate:
    path: /api/token/invalidate
```

If I remove `controller: gesdinet.jwtrefreshtoken::refresh` I get this error:

> Unable to find the controller for path "/api/token/refresh". The route is wrongly configured.

**Comment by blosky01** [comment]
The controller must be.
Maybe you can try to remove gesdinet and install again (Clear cache too).
I have this in my composer.json:
`"gesdinet/jwt-refresh-token-bundle": "dev-master",`

**Comment by valentin-harrang** [comment]
@blosky01 same problem after clearing cache and same after installed `"gesdinet/jwt-refresh-token-bundle": "dev-master",`

**Comment by blosky01** [comment]
Security.yaml:

`            refresh_jwt:
                check_path: /api/auth/refresh
                provider: app_user_provider
            switch_user: false`

--- 

routes.yaml:

`api_refresh_token:
  path: /api/auth/refresh    
  controller: gesdinet.jwtrefreshtoken::refresh`

---

Services.yaml:

`    App\OpenApi\RefreshTokenDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: [ '@.inner' ]`

---

in src/Entity/OpenApi/RefreshTokenDecorator.php 

`<?php
declare(strict_types=1);

namespace App\OpenApi;

use ApiPlatform\Core\OpenApi\Factory\OpenApiFactoryInterface;
use ApiPlatform\Core\OpenApi\OpenApi;
use ApiPlatform\Core\OpenApi\Model;

final class RefreshTokenDecorator implements OpenApiFactoryInterface
{
    public function __construct(
        private OpenApiFactoryInterface $decorated
    ) {}

    public function __invoke(array $context = []): OpenApi
    {
        $openApi = ($this->decorated)($context);
        $schemas = $openApi->getComponents()->getSchemas();

        $schemas['RefreshToken'] = new \ArrayObject([
            'type' => 'object',
            'properties' => [],
        ]);
        $schemas['RefreshCredentials'] = new \ArrayObject([
            'type' => 'object',
            'properties' => [],
        ]);

        $pathItem = new Model\PathItem(
            ref: 'Refresh JWT Token',
            post: new Model\Operation(
                operationId: 'postCredentialsItem',
                tags: ['Refresh Token'],
                responses: [
                    '200' => [
                        'description' => 'Get JWT token',
                        'content' => [
                            'application/json' => [
                                'schema' => [
                                    '$ref' => '#/components/schemas/RefreshToken',
                                ],
                            ],
                        ],
                    ],
                ],
                summary: 'Refresh JWT By Cookies',
                requestBody: new Model\RequestBody(
                    description: 'Generate new JWT Token',
                    content: new \ArrayObject([
                        'application/json' => [
                            'schema' => [
                                '$ref' => '#/components/schemas/RefreshCredentials',
                            ],
                        ],
                    ]),
                ),
            ),
        );
        $openApi->getPaths()->addPath('/api/auth/refresh', $pathItem);

        return $openApi;
    }
}`

---

 in src/Entity/RefreshToken

`<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken as BaseRefreshToken;

#[ORM\Table(name: '`refresh_tokens`')]
#[ORM\Entity()]
class RefreshToken extends BaseRefreshToken
{
}
`

Maybe this can help you.
if it doesn't work contact me.

**Comment by valentin-harrang** [comment]
@blosky01 thank you

Can you paste your security.yaml please ?

**Comment by blosky01** [comment]
security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto
            cost: 15
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
        # users_in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            json_login:
                check_path: /api/auth/login
                username_path: userIdentifier
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

            refresh_jwt:
                check_path: /api/auth/refresh
                provider: app_user_provider
            switch_user: false

    access_control:
        - { path: ^/api/auth/(login|refresh), roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon

**Comment by valentin-harrang** [comment]
@blosky01 Thank you (it's difficult to read your security.yaml ^^). I think it works, when I make a `POST` request to `/api/token/refresh`, the results contains a `token` and `refresh_token` ?

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/19478137/166913925-a65fd6bd-0b09-46da-9628-7ac0849a696d.png">

security.yaml:
```
security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        user:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            provider: user
            entry_point: form_login
            custom_authenticators:
                - App\Security\AdminAuthenticator
            form_login:
                provider: user
                login_path: admin_login
                check_path: admin_login_check
                failure_path: admin_login
                default_target_path: admin
                use_forward: false
                use_referer: true
                enable_csrf: true
            logout:
                path: admin_logout
                target: admin_login

        api:
            pattern: ^/api
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            entry_point: jwt
            jwt: ~
            refresh_jwt:
                check_path: /api/token/refresh
                provider: user
            switch_user: false
            logout:
                path: api_token_invalidate

    access_control:
        - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }
        - { path: ^/api/docs, roles: ROLE_ADMIN }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
```

routes.yaml:

```
api_login_check:
    path: /api/login
    methods: ['POST']

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_token_refresh:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh

api_token_invalidate:
    path: /api/token/invalidate
```

**Comment by blosky01** [comment]
Sorry for my security.yaml😅 
I hope I was able to help you solve you problem!🤜🏼🤛🏼

**Comment by valentin-harrang** [comment]
No problem, thank you! 👌🙂

**Comment by mbabker** [comment]
Remove the `controller: gesdinet.jwtrefreshtoken::refresh` config from the route.  That line is only required for folks using Symfony 4.4 applications and will break a Symfony 6 application because the Security-Guard component is not supported on Symfony 6.

**Comment by GeoDaz** [comment]
I used to migrate from symfony 5 to symfony 6 (nearly a year ago). This morning I came across this error, with no particular reason. I just add nelmio cors in dev mode for cors problem, a few days ago.

I had this (which was working in symfony 6 until now):
config/routes.yaml 
```yml
gesdinet_jwt_refresh_token:
  path: /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh
```
So I changed to this, to follow this issue resolution: 
```yml
api_refresh_token:
  path: /api/token/refresh
```
And now, I have : 
`Unable to find the controller for path "/api/token/refresh". The route is wrongly configured.`
I've update the bundle version from 1.1 to 1.2 and nothing changes.
I'm on sf 6, so following the previous comment, I should not meet that error ?

The rest of my configuration :
I had this but I think it's now (or has always been) useless : 
config/routes/gesdinet_jwt_refresh_token.yaml
```yml
gesdinet_jwt_refresh_token:
    path: /api/token/refresh

```
So I delete it.

config/packages/security.yml : 
```yml
security:
    ...
    firewalls:

        login:
            pattern: ^/api/login
            user_checker: App\Security\UserChecker
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
  
        refresh:
            pattern: ^/api/token/refresh
            stateless: true
            user_checker: App\Security\UserChecker
            refresh_jwt: ~
```

config/packages/gesdinet_jwt_refresh_token.yaml
```yml
gesdinet_jwt_refresh_token:
  ttl_update: true
  refresh_token_class: App\Entity\RefreshToken
```
