### ISSUE TITLE
Symfony 5.4: AbstractRefreshToken deprecated

### ISSUE THREAD

**Issue by disstudio** [markitosgv/JWTRefreshTokenBundle#301]
Installed v1.0.1

My configuration:
```
# config/packages/gesdinet_jwt_refresh_token.yaml
gesdinet_jwt_refresh_token:
  ttl: '%jwt.refresh_token_ttl%'
  token_parameter_name: refreshToken
```

Giving this message:
`Since gesdinet/jwt-refresh-token-bundle 1.0: The "Gesdinet\JWTRefreshTokenBundle\Entity\AbstractRefreshToken" class is deprecated, use "Gesdinet\JWTRefreshTokenBundle\Model\AbstractRefreshToken" instead.`

Trying manually configure arguments to service:
```
#config/services.yaml
services:
  gesdinet.jwtrefreshtoken.refresh_token_manager:
    class: Gesdinet\JWTRefreshTokenBundle\Doctrine\RefreshTokenManager
    public: true
    arguments: [ '@doctrine.orm.default_entity_manager', 'Gesdinet\JWTRefreshTokenBundle\Model\AbstractRefreshToken']
```
results to an error: `The class 'Gesdinet\JWTRefreshTokenBundle\Model\AbstractRefreshToken' was not found in the chain configured namespaces App\Entity, ... , Gesdinet\JWTRefreshTokenBundle\\Entity`

**Comment by devleesch001** [comment]
Same

**Comment by JeremyCoutellec** [comment]
Same for me

**Comment by Eimantas123** [comment]
You are missing:
`refresh_jwt: ~`
inf security yaml, check documentation of new version.

**Comment by Eimantas123** [comment]
@vandal-kherson I had this problem also, I'm just saying how I fixed it. There is a thread somewhere that if there is controller defined it uses old version of refresh token code, which uses AbstractGuardAuthenticator and if you remove it, then it does not use it. Check if you have added `refresh_jwt: ~` in security.yaml. For me it was those 2 steps to fix this issue.

**Comment by vandal-kherson** [comment]
> ses old version of refresh token code, which uses AbstractGuardAuthenticator and if you remove it, then it does not use it. Check if you have added `refresh_jwt: ~` in security.yaml. For me it was those 2 steps to fix this issue. Also note that those steps are for v1.0.1 if you use other one version than it might be other issue.

How you fix error like "Unable to find the controller for path "/security/token/refresh". The route is wrongly configured."?

**Comment by disstudio** [comment]
> Remove `controller: gesdinet.jwtrefreshtoken::refresh` part in routes.yaml and you might be missing: `refresh_jwt: ~` in security.yaml, check documentation of new version configs.
This line is removed:
```
# config/routes.yaml
gesdinet_jwt_refresh_token:
  path:       /api/token/refresh

api_gesdinet_jwt_refresh_token:
  path:       /api/admin/token/refresh
```

```
# config/packages/security.yaml
  firewalls:

    refresh:
      pattern:  ^/api/token/refresh
      provider: entity_provider
      stateless: true
      refresh_jwt: ~

    refresh_admin:
      pattern:  ^/api/admin/token/refresh
      provider: app_admin_provider
      stateless: true
      refresh_jwt: ~
```

**Comment by badr-ou** [comment]
Same for me @markitosgv is it regression ?

**Comment by mbabker** [comment]
The 1.1 release should fix this.

**Comment by BernardA** [comment]
@mbabker, I am afraid not.

I just upgraded to v.1.1.1 - Symfony 5.4 and have the same issue:

My configuration:

/config/packages/security.yaml

      firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            custom_authenticators:
                - app.google_login_authenticator
                - App\Security\TokenAuthenticator
            entry_point: App\Security\TokenAuthenticator
            user_checker: App\Security\UserEnabledChecker
            refresh_jwt:
                check_path: /api/token/refresh

/config/routes.yaml

        gesdinet_jwt_refresh_token:
              path: /api/token/refresh

**Comment by mbabker** [comment]
Which error are you getting?  There are a few of them mentioned in this issue.  The 1.1 release fixed the routing-related quirks when hitting the refresh endpoint without a refresh token (which, with your config, that issue should be gone).  It didn't fix the `AbstractRefreshToken` class deprecation, that one can only be fixed inside your app if you're extending from that class (nothing in the bundle is using that class).  And if you're getting the `AbstractGuardAuthenticator` error, check all of the authenticators your app is using to make sure none of them use the deprecated Security-Guard component (some packages, like this one and the LexikJWTAuthenticationBundle, are still shipping classes extending the deprecated class, but that's not an issue for you as long as you aren't using them).

**Comment by Jayfrown** [comment]
@BernardA the initial problem was that the `refresh_jwt` authenticator would only support requests where the `refresh_token` was available. If it was not available in the request, the authenticator would not support it, and thus things fall back to requiring a controller definition in the route.

That meant an empty GET request would result in a 404 if no controller was set. Even then, without a controller in the route definition, the authenticator worked fine if the `refresh_token` *was* set in the request. That issue is fixed in the latest release, by testing for the `check_path` configuration instead of the presence of a `refresh_token`.

In your current configuration, does the `refresh_jwt` authenticator process requests where the `refresh_token` is set correctly? If that is not the case, it might be that something in your configuration is blocking the `refresh_jwt` authenticator from triggering at all. Maybe other authenticators trigger before it does.

Also, as you have the route named in your `routes.yaml` you can configure the `check_path` with the named route (ie. `check_path: gesdinet_jwt_refresh_token`)

For reference, my (working) configuration is as follows:

<details>
<summary>expand configuration</summary>

```yaml
# security.yaml
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_docs:
            pattern: ^/api/docs
            stateless: true
        api:
            pattern: ^/api
            stateless: true
            provider: chain_provider
            entry_point: jwt
            jwt: ~
            json_login_ldap:
                service: Symfony\Component\Ldap\Ldap
                dn_string: 'uid={username},%env(resolve:LDAP_BASE_DN)%'
                check_path: api_token_auth
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
            refresh_jwt:
                check_path: api_token_refresh
            logout:
                path: api_token_invalidate
```

```yaml
# routes.yaml
api_token_auth:
    path: /api/token/auth
    methods: ['POST']

api_token_refresh:
    path: /api/token/refresh
    methods: ['POST']

api_token_invalidate:
    path: /api/token/invalidate
    methods: ['POST']
```

</details>
