### ISSUE TITLE
How to disable table auto-generation `refresh_tokens`???

### ISSUE THREAD

**Issue by PHPTCloud** [markitosgv/JWTRefreshTokenBundle#305]
I implemented a new entity (App\Entity\RefreshToken extends your AbstractRefreshToken), but still getting default refresh_tokens table.

How to disable table auto-generation `refresh_tokens`???

`config/packages/gesdinet_jwt_refresh_token.yaml`
```
gesdinet_jwt_refresh_token:
  token_parameter_name: refresh_token
  refresh_token_class: App\Entity\RefreshToken
  doctrine_mappings: false

```
