### ISSUE TITLE
Issue in entity for refresh tokens

### ISSUE THREAD

**Issue by balvirsingh** [markitosgv/JWTRefreshTokenBundle#315]
gesdinet_jwt_refresh_token.yaml
Code is - 
gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\JwtRefreshToken
   
Entity file code is -  
JwtRefreshToken.php

 namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken;

/**
 * This class extends Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken to have another table name.
 *
 * @ORM\Entity
 * @ORM\Table("jwt_refresh_token")
 */
class JwtRefreshToken extends RefreshToken
{
}

But now issue showing that  - 

![image](https://user-images.githubusercontent.com/5753046/163003597-1643a8f2-f75d-41cb-83ad-2618e0dde43f.png)

If I set primary Id in entity file then it ask to implement the interface.
After implement interface and decalare all the methods of interface in entity file then again it gives error of mapping repository with interface. 
php version - 7.4
symfony version  - 5.2.5
Bundle version  - v1.0.0-beta4

**Comment by mbabker** [comment]
> symfony version - 5.2.5
> Bundle version - v1.0.0-beta4

Please update to Symfony 5.4 and the bundle's 1.1 release and check again.

**Comment by balvirsingh** [comment]
Thanks everyone, It works with version 0.12.

Now I have a query - 
I want to invalidate/expire the old jwt token when generate new token with refresh token.
Currently, Both old and new token are working. 

Thanks in advance.

**Comment by mbabker** [comment]
You'd have to do something to track issued JWTs in your app, out-of-the-box the LexikJWTAuthenticationBundle doesn't have any services to deal with that.

**Comment by Terroraapje** [comment]
Having the same issue on v1.1.1.
Running Symfony v6.0.*
PHP 8.1.

**Comment by mbabker** [comment]
> Are we missing annotations on the Base Class?

No.  The bundle provides an XML mapping for the base classes for the MongoDB ODM and ORM integrations.  Generally, that mapping should automatically be registered through the DoctrineBundle and Symfony's Doctrine Bridge component as long as you have the automapping option for your object manager enabled.  Or, if you don't want automapping enabled, you'd need to register the bundle mappings explicitly in your app's config.

**Comment by WebDaMa** [comment]
> > Are we missing annotations on the Base Class?
> 
> No. The bundle provides an XML mapping for the base classes for the MongoDB ODM and ORM integrations. Generally, that mapping should automatically be registered through whichever Doctrine bundle applies to your object manager and Symfony's Doctrine Bridge component as long as you have the automapping option for your object manager enabled. Or, if you don't want automapping enabled, you'd need to register the bundle mappings explicitly in your app's config.

Auto mapping was indeed not on. (project upgraded from SF4).
After enabling https://symfony.com/doc/current/reference/configuration/doctrine.html#custom-mapping-entities-in-a-bundle it works :)

**Comment by shakaran** [comment]
@mbabker diagnosed this correctly and @WebDaMa confirmed it: `auto_mapping` was off, so the bundle's XML mapping for the base class was never registered and the class extending it inherited nothing. A project upgraded from Symfony 4, as @WebDaMa's was, is exactly where that turns up.

It is the same cause as #339, and as of 6b0cfb8 it is written down rather than living in these threads. The README now names the error, explains that the base class carries its mapping and that Doctrine only registers it while `auto_mapping` is true, and gives the mapping to declare when it is not:

```yaml
# config/packages/doctrine.yaml
doctrine:
    orm:
        auto_mapping: false
        mappings:
            App:
                # ... your own mapping
            GesdinetJWTRefreshToken:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/vendor/gesdinet/jwt-refresh-token-bundle/config/doctrine'
                prefix: 'Gesdinet\JWTRefreshTokenBundle\Entity'
```

Note the path: this used to live under `Resources/config/doctrine`, and answers of that vintage still say so. It moved in 2.0.

**@balvirsingh, on your second question** — invalidating the old JWT when a new one is issued — @mbabker's answer was right in 2022 and is now out of date. LexikJWTAuthenticationBundle 3.x ships a token blocklist:

```yaml
lexik_jwt_authentication:
    blocklist_token:
        enabled: true
        cache: cache.app
```

That gives you `BlockedTokenManagerInterface`, and Lexik already blocks tokens on logout and login failure. Doing it on refresh is not automatic yet, and I have written up why on #327, along with what it would take.

Closing this as a duplicate of #339, now documented.
