### ISSUE TITLE
Can't configure refresh token with SF6

### ISSUE THREAD

**Issue by sanchobouillant** [markitosgv/JWTRefreshTokenBundle#330]
Hi everyone,

I try to configure the bundle with SF6 AND php8.1

routes.yaml

```
gesdinet_jwt_refresh_token:
  path: /auth-token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh
```

security.yaml

```
    login:
      pattern: ^/auth-token
      user_checker: App\Security\UserChecker
      stateless: true
      json_login:
        check_path: /auth-token
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    refresh:
      pattern: ^/auth-token/refresh
      user_checker: App\Security\UserChecker
      stateless: true
      refresh_jwt: ~
      provider: app_user_provider

    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      user_checker: App\Security\UserChecker
      stateless: true
      jwt: ~
      entry_point: jwt
```

With that code I have

>     Attempted to load class \"AbstractGuardAuthenticator\" from namespace \"Symfony\\Component\\Security\\Guard\".\nDid you forget a \"use\" statement for another namespace?

If I remove the controller part from the routes.yaml I have:

> Unable to find the controller for path \"/auth-token/refresh\". The route is wrongly configured.

What did I missed in my configuration?

**Comment by sanchobouillant** [comment]
Whenb I remove the controller and add the provider. I have 

`Unable to find the controller for path \"/auth-token/refresh\". The route is wrongly configured.`


security.yaml

```
    api_token_refresh:
      pattern: ^/auth-token/refresh
      stateless: true
      provider: app_user_provider
      refresh_jwt: ~
```

routes.yaml

```
api_refresh_token:
  path: /auth-token/refresh
```

**Comment by boxedcode** [comment]
@sanchobouillant Did you ever find a solution for this? I'm also facing the same issue.

**Comment by fico7489** [comment]
same here

**Comment by yo1nick** [comment]
Remove config/routes/gesdinet_jwt_refresh_token.yaml

**Comment by sanchobouillant** [comment]
It work but there are some deprecated warning
routes.yaml:
```
api_login_check:
  path: /auth-token

gesdinet_jwt_refresh_token:
  path: /api/token/refresh
```

security:

```
    login:
      pattern: ^/auth-token
      user_checker: App\Security\UserChecker
      stateless: true
      json_login:
        check_path: /auth-token
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure


    main:
      lazy: true
      provider: app_user_provider
      user_checker: App\Security\UserChecker
      stateless: true
      jwt: ~
      entry_point: jwt
      refresh_jwt:
        check_path: gesdinet_jwt_refresh_token
```

**Comment by shakaran** [comment]
@sanchobouillant, @boxedcode, @fico7489 — found it, and it is not what the error says. Documented in dbc4853.

@programmador was right that `controller:` had to go, and that fixed the first error, the missing `AbstractGuardAuthenticator`. What it then uncovered is a second, separate problem, which is why the advice looked like it had not worked.

**`refresh_jwt: ~` listens on `/login_check`.** `check_path` decides which requests the authenticator takes over, and it defaults to `/login_check` — Lexik's *login* path, which makes no sense for refreshing but is the convention the default came from. Left alone, the authenticator never sees your refresh route. The request carries on to the router, which finds the route you defined and nothing behind it:

```text
Unable to find the controller for path "/auth-token/refresh". The route is wrongly configured.
```

The route is fine. The message names the wrong thing entirely.

I reproduced it on a current Symfony to be sure. With `refresh_jwt: ~` the log says it outright:

```text
[info] Matched route "api_refresh_token".
[debug] Authenticator does not support the request.
[warning] Unable to look for the controller as the "_controller" parameter is missing.
```

Setting `check_path` to the same path — or to the route name — and the authenticator takes the request and goes to look the token up, as it should:

```yaml
security:
    firewalls:
        refresh:
            pattern: ^/auth-token/refresh
            stateless: true
            provider: app_user_provider
            refresh_jwt:
                check_path: /auth-token/refresh
```

@emits-web-solutions, deleting `config/routes/gesdinet_jwt_refresh_token.yaml` worked for the same reason from the other end: it removed the route the router was matching, so the request stopped reaching a route with no controller. It works, but you also lose the route, and defining it with a matching `check_path` is what you actually want.

@sanchobouillant, your final configuration has a `refresh` firewall *and* a `refresh_jwt` on `main` pointing at `gesdinet_jwt_refresh_token`. Only one of those is doing anything — whichever firewall matches the path first. On current versions there is no need for a separate firewall at all: `refresh_jwt` goes inside the API firewall alongside `jwt`.

The README now says all of this where the route is defined, and the note is on the `check_path` node itself so it shows up in `config:dump-reference`. Closing this.
