### ISSUE TITLE
Compatibility bug with Symfony 6.1 & ApiPlatform 3.0

### ISSUE THREAD

**Issue by ppoz21** [markitosgv/JWTRefreshTokenBundle#342]
Hi everyone,

I have problem with Symfony 6.1.0 and ApiPlatform 3.0.0

After installing bundle via composer all my API routes disappeared (only LexikJWT route added by OpenAPI decorator left)

![image](https://user-images.githubusercontent.com/35171722/192093934-5a78b557-9f7e-4845-9bb1-9795daedbeda.png)

When I remove bundle from bundles.php all endpoints return

![image](https://user-images.githubusercontent.com/35171722/192093996-027c94a1-be08-4ae7-95c0-33a8d5c5913d.png)

Here is my code:

`RefreshToken.php`
```php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken as BaseRefreshToken;

#[ORM\Entity]
#[ORM\Table('`refresh_tokens`')]
class RefreshToken extends BaseRefreshToken
{
}

```

`security.yaml`
```yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    enable_authenticator_manager: true
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            stateless: true
            provider: app_user_provider
            entry_point: jwt
            json_login:
                check_path: /authentication_token
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~
            refresh_jwt:
                check_path: /token/refresh
                provider: app_user_provider

    access_control:
        - { path: ^/authentication_token, roles: PUBLIC_ACCESS }
        - { path: ^/token/refresh, roles: PUBLIC_ACCESS }
        - { path: ^/api$, roles: PUBLIC_ACCESS }
#        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
```

Anyone have any solution?

**Comment by dutchtux3000** [comment]
I got the same problem here too.
I just see that when enabling the bundle all the routes of the Entities disappear from the routes list.

**With bundle enabled**
```
-------------------------- -------- -------- ------ ------------------------------------- --------------------------------------------------------- 
  Name                       Method   Scheme   Host   Path                                  Controller                                               
 -------------------------- -------- -------- ------ ------------------------------------- --------------------------------------------------------- 
  _preview_error             ANY      ANY      ANY    /_error/{code}.{_format}              error_controller::preview()                              
  _wdt                       ANY      ANY      ANY    /_wdt/{token}                         web_profiler.controller.profiler::toolbarAction()        
  _profiler_home             ANY      ANY      ANY    /_profiler/                           web_profiler.controller.profiler::homeAction()           
  _profiler_search           ANY      ANY      ANY    /_profiler/search                     web_profiler.controller.profiler::searchAction()         
  _profiler_search_bar       ANY      ANY      ANY    /_profiler/search_bar                 web_profiler.controller.profiler::searchBarAction()      
  _profiler_phpinfo          ANY      ANY      ANY    /_profiler/phpinfo                    web_profiler.controller.profiler::phpinfoAction()        
  _profiler_xdebug           ANY      ANY      ANY    /_profiler/xdebug                     web_profiler.controller.profiler::xdebugAction()         
  _profiler_search_results   ANY      ANY      ANY    /_profiler/{token}/search/results     web_profiler.controller.profiler::searchResultsAction()  
  _profiler_open_file        ANY      ANY      ANY    /_profiler/open                       web_profiler.controller.profiler::openAction()           
  _profiler                  ANY      ANY      ANY    /_profiler/{token}                    web_profiler.controller.profiler::panelAction()          
  _profiler_router           ANY      ANY      ANY    /_profiler/{token}/router             web_profiler.controller.router::panelAction()            
  _profiler_exception        ANY      ANY      ANY    /_profiler/{token}/exception          web_profiler.controller.exception_panel::body()          
  _profiler_exception_css    ANY      ANY      ANY    /_profiler/{token}/exception.css      web_profiler.controller.exception_panel::stylesheet()    
  auth_user_login            POST     ANY      ANY    /authentication/user/login                                                                     
  auth_user_refresh          ANY      ANY      ANY    /authentication/user/refresh                                                                   
  api_genid                  ANY      ANY      ANY    /api/.well-known/genid/{id}           api_platform.action.not_exposed()                        
  api_entrypoint             ANY      ANY      ANY    /api/{index}.{_format}                api_platform.action.entrypoint()                         
  api_doc                    ANY      ANY      ANY    /api/docs.{_format}                   api_platform.action.documentation()                      
  api_jsonld_context         ANY      ANY      ANY    /api/contexts/{shortName}.{_format}   api_platform.jsonld.action.context()                     
 -------------------------- -------- -------- ------ ------------------------------------- --------------------------------------------------------- 
```

**With bundle disabled:**
```
 ----------------------------------------- -------- -------- ------ ------------------------------------- --------------------------------------------------------- 
  Name                                      Method   Scheme   Host   Path                                  Controller                                               
 ----------------------------------------- -------- -------- ------ ------------------------------------- --------------------------------------------------------- 
  _preview_error                            ANY      ANY      ANY    /_error/{code}.{_format}              error_controller::preview()                              
  _wdt                                      ANY      ANY      ANY    /_wdt/{token}                         web_profiler.controller.profiler::toolbarAction()        
  _profiler_home                            ANY      ANY      ANY    /_profiler/                           web_profiler.controller.profiler::homeAction()           
  _profiler_search                          ANY      ANY      ANY    /_profiler/search                     web_profiler.controller.profiler::searchAction()         
  _profiler_search_bar                      ANY      ANY      ANY    /_profiler/search_bar                 web_profiler.controller.profiler::searchBarAction()      
  _profiler_phpinfo                         ANY      ANY      ANY    /_profiler/phpinfo                    web_profiler.controller.profiler::phpinfoAction()        
  _profiler_xdebug                          ANY      ANY      ANY    /_profiler/xdebug                     web_profiler.controller.profiler::xdebugAction()         
  _profiler_search_results                  ANY      ANY      ANY    /_profiler/{token}/search/results     web_profiler.controller.profiler::searchResultsAction()  
  _profiler_open_file                       ANY      ANY      ANY    /_profiler/open                       web_profiler.controller.profiler::openAction()           
  _profiler                                 ANY      ANY      ANY    /_profiler/{token}                    web_profiler.controller.profiler::panelAction()          
  _profiler_router                          ANY      ANY      ANY    /_profiler/{token}/router             web_profiler.controller.router::panelAction()            
  _profiler_exception                       ANY      ANY      ANY    /_profiler/{token}/exception          web_profiler.controller.exception_panel::body()          
  _profiler_exception_css                   ANY      ANY      ANY    /_profiler/{token}/exception.css      web_profiler.controller.exception_panel::stylesheet()    
  auth_user_login                           POST     ANY      ANY    /authentication/user/login                                                                     
  auth_user_refresh                         ANY      ANY      ANY    /authentication/user/refresh                                                                   
  api_genid                                 ANY      ANY      ANY    /api/.well-known/genid/{id}           api_platform.action.not_exposed()                        
  api_entrypoint                            ANY      ANY      ANY    /api/{index}.{_format}                api_platform.action.entrypoint()                         
  api_doc                                   ANY      ANY      ANY    /api/docs.{_format}                   api_platform.action.documentation()                      
  api_jsonld_context                        ANY      ANY      ANY    /api/contexts/{shortName}.{_format}   api_platform.jsonld.action.context()                     
  _api_/students/{id}.{_format}_get         GET      ANY      ANY    /api/students/{id}.{_format}          api_platform.action.placeholder()                        
  _api_/students.{_format}_get_collection   GET      ANY      ANY    /api/students.{_format}               api_platform.action.placeholder()                        
  _api_/students.{_format}_post             POST     ANY      ANY    /api/students.{_format}               api_platform.action.placeholder()                        
  _api_/students/{id}.{_format}_put         PUT      ANY      ANY    /api/students/{id}.{_format}          api_platform.action.placeholder()                        
  _api_/students/{id}.{_format}_patch       PATCH    ANY      ANY    /api/students/{id}.{_format}          api_platform.action.placeholder()                        
  _api_/students/{id}.{_format}_delete      DELETE   ANY      ANY    /api/students/{id}.{_format}          api_platform.action.placeholder()                        
  _api_/users/{id}.{_format}_get            GET      ANY      ANY    /api/users/{id}.{_format}             api_platform.action.placeholder()                        
  _api_/users.{_format}_get_collection      GET      ANY      ANY    /api/users.{_format}                  api_platform.action.placeholder()                        
  _api_/users.{_format}_post                POST     ANY      ANY    /api/users.{_format}                  api_platform.action.placeholder()                        
  _api_/users/{id}.{_format}_put            PUT      ANY      ANY    /api/users/{id}.{_format}             api_platform.action.placeholder()                        
  _api_/users/{id}.{_format}_patch          PATCH    ANY      ANY    /api/users/{id}.{_format}             api_platform.action.placeholder()                        
  _api_/users/{id}.{_format}_delete         DELETE   ANY      ANY    /api/users/{id}.{_format}             api_platform.action.placeholder()                        
 ----------------------------------------- -------- -------- ------ ------------------------------------- --------------------------------------------------------- 
```
I use the same configuration that @ppoz21 is given in the example above.

**Comment by tamsirgueye** [comment]
Hi!
>
I use google translation.
>
I have the same problem also.
>
First of all the bundle disrupted the functioning of the maker-bundle. Take a look at [this issue](https://github.com/symfony/maker-bundle/issues/1212#issuecomment-1261002322).
>
Then after configuration all my routes that are generated with the `#[ApiResource]` attribute disappear completely.
>
I think the bundle is not ready for symfony 6 yet

**Comment by dutchtux3000** [comment]
I think the problem is that entity is using the old style annotation of doctrine instead of the PHP 8 attributes.

**Comment by mbabker** [comment]
> I think the problem is that entity is using the old style annotation of doctrine instead of the PHP 8 attributes.

The doc examples and the file added by the Flex recipe use annotations, but if your application is using attributes, you can update the code in your application to use those.  Annotations use is still valid on PHP 8, but the ecosystem is moving away from it (if everything only documented/configured attributes by default, then folks running on PHP 7 would have broken apps; it's one of those "you can't win them all" situations).

**Comment by erikkubica** [comment]
Hi everyone, is there any workaround? 

As described by others, API platform API resources  are debug-able but they don't appear in routing therefore they don't appear in swagger. It feels like it's preventing API platform from registering routes which makes no sense to me if it's not decorated with the #[ApiResource]

I have changed my RefreshToken entity to
```<?php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken as BaseRefreshToken;

#[ORM\Entity]
#[ORM\Table(name: 'refresh_tokens')]
class RefreshToken extends BaseRefreshToken { }
```
security.yml
```
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|docs.jsonld|docs|nextjs)/
            security: false
        main:
            pattern: ^/
            stateless: true
            lazy: true
            provider: app_user_provider
            entry_point: jwt
            json_login:
                check_path: /token/request
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~
            refresh_jwt:
                check_path: /token/refresh

    access_control:
        - { path: ^/(docs|docs.jsonld), roles: PUBLIC_ACCESS }
        - { path: ^/token/(refresh|request), roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: PUBLIC_ACCESS }
        - { path: ^/form_datas/submit/*/*, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
```
routes/token.yml
```
token_request:
    path: /token/request
    methods: [ 'POST' ]

token_refresh:
    path:       /token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
```

```
/srv/app # php bin/console debug:router
 -------------------------- -------- -------- ------ ----------------------------------- 
  Name                       Method   Scheme   Host   Path                               
 -------------------------- -------- -------- ------ ----------------------------------- 
  api_genid                  ANY      ANY      ANY    /.well-known/genid/{id}            
  api_entrypoint             ANY      ANY      ANY    /{index}.{_format}                 
  api_doc                    ANY      ANY      ANY    /docs.{_format}                    
  api_jsonld_context         ANY      ANY      ANY    /contexts/{shortName}.{_format}    
  _preview_error             ANY      ANY      ANY    /_error/{code}.{_format}           
  token_request              POST     ANY      ANY    /token/request                     
  token_refresh              ANY      ANY      ANY    /token/refresh                     
  _wdt                       ANY      ANY      ANY    /_wdt/{token}                      
  _profiler_home             ANY      ANY      ANY    /_profiler/                        
  _profiler_search           ANY      ANY      ANY    /_profiler/search                  
  _profiler_search_bar       ANY      ANY      ANY    /_profiler/search_bar              
  _profiler_phpinfo          ANY      ANY      ANY    /_profiler/phpinfo                 
  _profiler_xdebug           ANY      ANY      ANY    /_profiler/xdebug                  
  _profiler_search_results   ANY      ANY      ANY    /_profiler/{token}/search/results  
  _profiler_open_file        ANY      ANY      ANY    /_profiler/open                    
  _profiler                  ANY      ANY      ANY    /_profiler/{token}                 
  _profiler_router           ANY      ANY      ANY    /_profiler/{token}/router          
  _profiler_exception        ANY      ANY      ANY    /_profiler/{token}/exception       
  _profiler_exception_css    ANY      ANY      ANY    /_profiler/{token}/exception.css   
```

**Comment by erikkubica** [comment]
Don't know what made a difference, maybe installing symfony then adding api-platform, but flex + api-platform actually works.

**Comment by shakaran** [comment]
@ppoz21, @dutchtux3000, @tamsirgueye, @erikkubica — I could not reproduce this on current versions, and I tried properly rather than assuming.

I built a project from scratch with Symfony 7, API Platform 4, Doctrine ORM 3 and this bundle from master, with one `#[ApiResource]` entity and a `RefreshToken` extending ours, and compared `debug:router` with the bundle registered in `bundles.php` and without it:

```
SIN bundle -> total: 15 | books: 5
CON bundle -> total: 15 | books: 5
```

Identical, and the bundle really is loaded in the second run — its services are in the container. I ran it both with `api_platform.mapping.paths` set explicitly and left to auto-detection, since that is the setting most likely to be disturbed by another bundle appearing. Same result both ways.

**Why it cannot happen now**, as far as the bundle is concerned: it registers no Doctrine mapping compiler pass, no route loader, and contributes no routes of its own. The refresh endpoint is a firewall authenticator, not a controller, so there is nothing in it that adds to or removes from the route collection.

What I cannot give you is the 2022 root cause. The reports were against Symfony 6.1 and API Platform 3.0.0, both long out of support, and against 1.x of this bundle, which differed in ways that matter here: it shipped a controller, it did not override `getPath()`, and its mapping lived under `Resources/config/doctrine`. Whether it was one of those or something in API Platform 3.0.0 itself, I would only be guessing, and @erikkubica's follow-up — that it worked when the install order changed — points at the environment rather than at either library.

**One thing worth flagging for anyone landing here from a search.** @erikkubica's `routes/token.yml` has:

```yaml
token_refresh:
    path:       /token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
```

That controller does not exist as of 2.0. Copying that today gives you a route pointing at a missing class, which is a different failure that looks similar from the outside. The route now needs no controller at all — the firewall answers the path before a controller would be reached. It is in the README.

Closing as not reproducible. If anyone still sees this on supported versions, please reopen with the Symfony and API Platform versions and I will dig in — I would rather chase it with a live case than a three-year-old one.
