### ISSUE TITLE
symfony 6.2: Unable to find the controller

### ISSUE THREAD

**Issue by dvdknaap** [markitosgv/JWTRefreshTokenBundle#356]
Tried the solutions in #307 but none of them are working.
I keep getting `Unable to find the controller for path "/api/token/refresh/". The route is wrongly configured`

it raises this error because in the `ControllerResolver` it cant find the `_controller` in the attribute request.

````
# security.yaml
    api_token_refresh:
      pattern: ^/api/token/refresh
      stateless: true
      provider: database_users
      refresh_jwt: ~
````

````
# config/routes/gesdinet_jwt_refresh_token.yaml (from flex)
gesdinet_jwt_refresh_token:
    path: /api/token/refresh

````

```
# config/routes.yaml
api_token_refresh:
  path: /api/token/refresh/ # the slash is needed at the end else it will not match the route
  methods: POST
```
