### ISSUE TITLE
Unrecognized option "anonymous" under "security.firewalls.refresh"

### ISSUE THREAD

**Issue by Huluti** [markitosgv/JWTRefreshTokenBundle#382]
This option is not available anymore. Removing it from the config fix the error.

```
Unrecognized option "anonymous" under "security.firewalls.refresh". Available options are "access_denied_handler", "access_denied_url", "access_token", "context", "custom_authenticators", "entry_point", "form_login", "form_login_ldap", "host", "http_basic", "http_basic_ldap", "json_login", "json_login_ldap", "jwt", "lazy", "login_link", "login_throttling", "logout", "methods", "pattern", "provider", "refresh_jwt", "remember_me", "remote_user", "request_matcher", "required_badges", "security", "stateless", "switch_user", "two_factor", "user_checker", "x509".
```

**Comment by shakaran** [comment]
You are right, and sorry for the two years of silence.

`anonymous` was removed in Symfony 6, along with the rest of the pre-authenticator security system. Nothing in the bundle needed it.

Where it came from was us. The README documented exactly this, down to the firewall name in your error:

```yaml
refresh:
    pattern:  ^/api/token/refresh
    stateless: true
    anonymous: true
```

So you did not add that option, you copied it from our own installation instructions, which were still showing the Symfony 5 configuration. Removing it was the right call.

That block is gone as of 2.0, and there is no separate `refresh` firewall any more. The authenticator goes inside the API firewall you already have:

```yaml
security:
    firewalls:
        api:
            pattern: ^/api
            stateless: true
            entry_point: jwt
            json_login:
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~
            refresh_jwt:
                check_path: /api/token/refresh
    access_control:
        - { path: ^/api/(login|token/refresh), roles: PUBLIC_ACCESS }
```

`PUBLIC_ACCESS` in `access_control` is what `anonymous: true` was reaching for.

I checked the whole repository and the option appears nowhere any more. Closing this as fixed in 2.0. Thanks for reporting it, and for pinning down the fix yourself.
