### ISSUE TITLE
CORS OPTIONS request to the token refresh endpoint gives a 401 Missing JWT Refresh Token

### ISSUE THREAD

**Issue by boodle** [markitosgv/JWTRefreshTokenBundle#393]
I have the refresh tokens up and working nicely, however a CORS preflight OPTIONS request to the refresh token endpoint gives the following:
```
{
    "code": 401,
    "message": "Missing JWT Refresh Token"
}
```

This is my `routes/gesdinet_jwt_refresh_token.yaml` where I try to restrict it to just POST requests:
```
gesdinet_jwt_refresh_token:
    path: /api/v1/token/refresh
    methods: ['POST']

api_token_invalidate:
    path: /api/v1/token/invalidate
    methods: ['POST']
```

Here's my `security.yaml` setup:
```
        api:
            pattern:   ^/api
            stateless: true
            entry_point: jwt
            json_login:
                check_path: /api/v1/login # or, if you have defined a route for your login path, the route name you used
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~
            refresh_jwt:
                check_path: /api/v1/token/refresh # or, you may use the `api_refresh_token` route name
            logout:
                path: api_token_invalidate
```

I have a generic preflight controller that I setup, which _should_ match the route I have configured - you can see it below as the top listed route as I set the routing priority high, in order to try and resolve this:
```
 --------------------------------------- ---------- -------- ------ --------------------------------------------- 
  Name                                    Method     Scheme   Host   Path                                         
 --------------------------------------- ---------- -------- ------ --------------------------------------------- 
  api:preflight:namespace:object          OPTIONS    ANY      ANY    /api/v1/{namespace}/{object}                 
  gesdinet_jwt_refresh_token              POST       ANY      ANY    /api/v1/token/refresh                        
 ### other routes removed for clarity ###
```

If I use `router:match` it says that my preflight controller should match:
![image](https://github.com/user-attachments/assets/c59d3234-8a0a-4e51-b385-bbe456cd9eb0)

However, if I test using Postman, or live in a browser, it fails unless a body is sent.

I can work around this using the apache / nginx config I think, but I feel I'm missing something.

Versions of stuff:
```
PHP 8.3
Symfony 7.1
gesdinet/jwt-refresh-token-bundle v1.4.0
lexik/jwt-authentication-bundle v2.21.0
```

Many thanks for this bundle BTW, it's really saving my bacon.
